sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t pieralukasz/sturdy-tribble -f Dockerfile.dev .

script:
  - docker run -e CI=true pieralukasz/sturdy-tribble npm test
